#ifndef PROC_GEN_OPENGL_CAMERA_TYPE_HPP
#define PROC_GEN_OPENGL_CAMERA_TYPE_HPP

enum CameraType
{
//	STATIC_CAMERA,
	ABOVE_CAMERA,
	FPS_CAMERA,
//	GROUNDED_FPS_CAMERA,
};

#endif //PROC_GEN_OPENGL_CAMERA_TYPE_HPP
